# Cargo configuration for faster builds

[build]
# Number of parallel jobs (adjust based on your CPU)
jobs = 8

# Use sccache if available for caching compiled dependencies
# Install with: cargo install sccache
# rustc-wrapper = "sccache"  # Commented out - uncomment if you have sccache installed

# Enable incremental compilation
incremental = true

# Split debuginfo for faster linking
[profile.dev]
split-debuginfo = "unpacked"

# Faster linker (mold is fastest, lld is good too)
# Uncomment the following if you have lld or mold installed:
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# Alternative: Use mold (even faster)
# Install with: sudo apt install mold
# Then uncomment:
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=mold"]

# Share generics between crates
[profile.dev.package."*"]
opt-level = 0
codegen-units = 256

[profile.release.package."*"]
opt-level = 2
codegen-units = 16